name = "CNNHelmholtzSolver"
uuid = "8b85f1ca-1b52-41dd-b549-f0c28c54321e"
authors = ["Matan Goren <matantheman@gmail.com>"]
version = "0.1.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
